# /* ---- 💫 https://github.com/0o0-ct/Pixi-Arch 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# --- 💫 Thunar Frosted Glass & Bright Fine Border Rules 💫 ---
windowrule = match:class ^(thunar)$, opacity 0.80 0.70
windowrule = match:class ^(thunar)$, border_size 1
windowrule = match:class ^(thunar)$, border_color rgba(ffffff66) rgba(ffffff1a)

